### ISSUE TITLE
Test failing with wrong spacing in the expected value of tests

### ISSUE THREAD

**Issue by demanuel** [jonathanstowe/JSON-Marshal#11]
Trying to update to latest version with raku from latest master:

```

===> Testing: JSON::Marshal:ver<0.0.21>:auth<github:jonathanstowe>:api<1.0>
[JSON::Marshal] # Failed test 'marshalled JSON is compact'
[JSON::Marshal] # at t/120-pretty.t line 37
[JSON::Marshal] # expected: "\{\"bool\":true,\"int\":42,\"str-array\":[\"one\",\"two\",\"three\"],\"string\":\"string\"}"
[JSON::Marshal] #      got: "\{\"bool\": true,\"int\": 42,\"str-array\": [\"one\",\"two\",\"three\"],\"string\": \"string\"}"
[JSON::Marshal] # You failed 1 test of 4
===> Testing [FAIL]: JSON::Marshal:ver<0.0.21>:auth<github:jonathanstowe>:api<1.0>
Aborting due to test failure: JSON::Marshal:ver<0.0.21>:auth<github:jonathanstowe>:api<1.0> (use --force-test to override)
```

Regards!

**Comment by jonathanstowe** [comment]
Gah.  Looks like a stupid test that does a string comparison.  Let's fix that.

**Comment by jonathanstowe** [comment]
What version of `JSON::Fast` do you have installed?  It gives the expected result for me with the `JSON::Fast:ver<0.16>`  and it's definitely the way the `JSON::Fast` outputs the JSON string that is causing what you are seeing.

I'm going to change the test so that it compares the output of `marshall` with the output of `to-json` with the appropriate flags regardless, but curious as to what version between `0.10` and `0.16` gave rise to the differing output.

**Comment by jonathanstowe** [comment]
The potential for this test to fail because of changes in the format of the JSON string emitted by JSON::Fast is fixed in the https://github.com/jonathanstowe/JSON-Marshal/releases/tag/v0.0.22.

**Comment by demanuel** [comment]
Does this helps?

zef info JSON::Fast
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated fez mirror: http://360.zef.pm/
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
- Info for: JSON::Fast
- Identity: JSON::Fast:ver<0.16>
- Recommended By: Zef::Repository::Ecosystems<cpan>
- Installed: Yes, as JSON::Fast:ver<0.9.8>
Description:	 A naive, fast json parser and serializer; drop-in replacement for JSON::Tiny
License:	 Artistic-2.0
Source-url:	 http://www.cpan.org/authors/id/T/TI/TIMOTIMO/Perl6/JSON-Fast-0.16.tar.gz
Provides: 1 modules
Support:
#   source:	git://github.com/timo/json_fast.git
Depends: 1 items

**Comment by demanuel** [comment]
With the latest version, the upgrade went without issues.
Thanks!

**Comment by jonathanstowe** [comment]
I think you just got unlucky with having the only version of JSON::Fast that formatted the compact JSON string differently.
