### ISSUE TITLE
Auto kebab case to _ case

### ISSUE THREAD

**Issue by Skarsnik** [jonathanstowe/JSON-Marshal#2]
It could be interesting to have something to tell marshal/unmarshal to automaticly convert kebab case to undercase (or even for CamelCase too maybe?)

**Comment by jonathanstowe** [comment]
Hi,
sorry I didn't reply sooner.

For the Marshal case (and probably Unmarshal but I'll let @tadzik respond to that,) I think that it would be an over-complication and would be better left to JSON::Name,  the complexity arises where there may be mixed CamelCase, snake_case and/or kebab-case in output JSON object, so this may require one or more addtional traits to hint at the appropriate conversion, at which point one may as well just type the desired name in a "json-name" trait. I guess that it is possible that one could add an ':auto' variant of the JSON::Name trait to do this, but it seems that would have the same complexity for the Unmarshal case.

My personal preference would be to put any really magic stuff into JSON::Infer which could generate the json-name traits for all the converted names (it currently only does it for names that are not valid identifiers.)

Thanks for the input :)

**Comment by jonathanstowe** [comment]
I'm going to close this after 5½ years because I still can't think of something that will work for everyone that is simpler than simply providing the name with `json-name` :-D
