### ISSUE TITLE
Test failures because of JSON::Fast

### ISSUE THREAD

**Issue by azawawi** [jonathanstowe/JSON-Marshal#3]
@jonathanstowe 

Please revert https://github.com/jonathanstowe/JSON-Marshal/commit/d3cf700eedebf2cfbd53d1d992914ded7b78e53e. It causing a lot of failures and  breaking future Test::META usage in my modules.

**Comment by jonathanstowe** [comment]
Upgrade to a newer version of JSON::Fast please, the previous one had a bug that prevented me from doing this earlier.

**Comment by azawawi** [comment]
So basically https://github.com/tadzik/panda/blob/master/ext/JSON__Fast/META6.json is the culprit?

**Comment by jonathanstowe** [comment]
Yes.  This is also compounded by the fact that panda is unable to handle versioned dependencies.  I'll pester someone to upgrade the JSON::Fast that is bundled with panda.

**Comment by jonathanstowe** [comment]
Hi,
The version of JSON::Fast bundled by panda has been bounced so this should be somewhat mitigated :)

**Comment by azawawi** [comment]
Looks good. Closing in 5 seconds...  Thanks for your time :+1:
