### ISSUE TITLE
hi, trying to use it I got this

### ISSUE THREAD

**Issue by bioduds** [jonathanstowe/JSON-Marshal#5]
ubuntu@ip-172-31-47-63:~/dev/futs/scripts$ panda install JSON::Marshal
==> Fetching JSON::Marshal
==> Building JSON::Marshal
==> Testing JSON::Marshal
t/010-use.t ........ ok
t/020-marshal.t .... ok
t/030-trait.t ...... ok
t/040-json-name.t .. ok
t/050-skip-null.t .. ok
t/060-array.t ...... ok
All tests successful.
Files=6, Tests=28,  4 wallclock secs ( 0.02 usr  0.01 sys +  3.75 cusr  0.26 csys =  4.04 CPU)
Result: PASS
==> Installing JSON::Marshal
JSON::Marshal:ver<0.0.10>:authgithub:jonathanstowe:api<> already installed
  in block  at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 61
  in sub indir at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 20
  in method install at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 42
  in method install at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 161
  in method resolve at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 234
  in sub MAIN at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 18
  in block <unit> at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 151

Actually thrown at:
  in method install at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 44
  in method install at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 161
  in method resolve at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 234
  in sub MAIN at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 18
  in block <unit> at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 151

ubuntu@ip-172-31-47-63:~/dev/futs/scripts$ perl6 get_data.pl 
Segmentation fault (core dumped)
ubuntu@ip-172-31-47-63:~/dev/futs/scripts$ perl6 get_data.pl 
Segmentation fault (core dumped)
ubuntu@ip-172-31-47-63:~/dev/futs/scripts$ perl6 get_data.pl 
Segmentation fault (core dumped)

THE CODE IS:
# !/usr/bin/env perl6

use v6;
use JSON::Marshal;

my &infix:<++> = &infix:<~>;
subset IdentStr of Str where /^<.ident>$/;
subset Gênero of Str where \* eq "Homem"|"Mulher";

class Técnico does JSON::Class {
  my $.identidade = "Técnico";
  has $.nome;
  has Gênero $.gênero;
  has Int $.idade;
  has Rat $.rate;
}

my Str @técnicos = marshal( Técnico.new( nome => "Marcelo Oliveira", gênero => "Homem", idade => 54, rate => 3.88 ) ), 
                   marshal( Técnico.new( nome => "Levir Culpi", gênero => "Homem", idade => 52, rate => 4.12 ) );

sub ef8a4da32a-get-json {
  say @técnicos;
}

ef8a4da32a-get-json;

**Comment by jonathanstowe** [comment]
Hi,
If I add the required `use JSON::Class;` the code runs fine for me with `This is Rakudo version 2016.09-7-g363a3a8 built on MoarVM version 2016.09`..

The output is:

```
[{
  "gênero": "Homem",
  "nome": "Marcelo Oliveira",
  "rate": 3.88,
  "idade": 54
} {
  "gênero": "Homem",
  "nome": "Levir Culpi",
  "rate": 4.12,
  "idade": 52
}]
```

Can you let me know which version of Rakudo you are trying to use?

**Comment by jonathanstowe** [comment]
BTW, what I would consider the more _idiomatic_ way of doing this (assuming you wanted an array of JSON strings) would be:

``` perl6
#!/usr/bin/env perl6
use v6;

use JSON::Class;

subset IdentStr of Str where /^<.ident>$/;
subset Gênero of Str where * eq "Homem"|"Mulher";

class Técnico does JSON::Class {
has $.identidade = "Técnico";
has $.nome;
has Gênero $.gênero;
has Int $.idade;
has Rat $.rate;
}

my Str @técnicos = ( Técnico.new( nome => "Marcelo Oliveira", gênero => "Homem", idade => 54, rate => 3.88 ) , 
                     Técnico.new( nome => "Levir Culpi", gênero => "Homem", idade => 52, rate => 4.12 ) ).map: *.to-json;

sub ef8a4da32a-get-json {
say @técnicos.perl;
}

ef8a4da32a-get-json;
```

If of course you wanted a single JSON string of the whole array in the end you could go for:

``` perl6
#!/usr/bin/env perl6
use v6;

use JSON::Class;

subset IdentStr of Str where /^<.ident>$/;
subset Gênero of Str where * eq "Homem"|"Mulher";

class Técnico does JSON::Class {
    has $.identidade = "Técnico";
    has $.nome;
    has Gênero $.gênero;
    has Int $.idade;
    has Rat $.rate;
}

my $técnicos = ( Técnico.new( nome => "Marcelo Oliveira", gênero => "Homem", idade => 54, rate => 3.88 ) , 
                 Técnico.new( nome => "Levir Culpi", gênero => "Homem", idade => 52, rate => 4.12 ) ) but JSON::Class;

sub ef8a4da32a-get-json {
    say $técnicos.to-json;
}

ef8a4da32a-get-json;
```

Other techniques are, of course, available :)

**Comment by jonathanstowe** [comment]
I'm going to close this now.
