### ISSUE TITLE
Could not find JSON::Fast:ver<0.4..*>

### ISSUE THREAD

**Issue by Altai-man** [jonathanstowe/JSON-Marshal#7]
Hello. I am not really sure if it is a JSON::Marshal problem, because lately there were some commits related to it to zef(notably https://github.com/ugexe/zef/commit/bf75d24da69eac3e86d1ba5104283c57d240dbd8 and https://github.com/ugexe/zef/commit/0ed9aabafe83950be0430ba57f55729afc72f570), so I am ready to re-post this issue to `zef` repository, just don't sure what the correct behavior must be.

On fresh rakudo and newly-built zef after installing of `JSON::Marshal`:
```
➜  1 git:(master) zef --installed list
===> Found via /home/sena/.rakudobrew/moar-nom/install/share/perl6
CORE:ver('6.c'):auth('perl')
===> Found via /home/sena/.rakudobrew/moar-nom/install/share/perl6/site
JSON::Fast:ver('0.9.1')             # === Here it is, nice and clear;
JSON::Marshal:ver('0.0.11'):auth('github:jonathanstowe')  # === And the last version is here too.
OpenSSL:ver('0.1.11'):auth('github:sergot')
zef:ver('0.1.25'):auth('github:ugexe')
JSON::Name:ver('0.0.2'):auth('github:jonathanstowe')
➜  1 git:(master) perl6
To exit type 'exit' or '^D'
> use JSON::Marshal;
===SORRY!===
Could not find JSON::Fast:ver<0.4..*> at line 60 in:  # === Bang!
    /home/sena/.perl6
    /home/sena/.rakudobrew/moar-nom/install/share/perl6/site
    /home/sena/.rakudobrew/moar-nom/install/share/perl6/vendor
    /home/sena/.rakudobrew/moar-nom/install/share/perl6
    CompUnit::Repository::AbsolutePath<65633296>
    CompUnit::Repository::NQP<52007704>
    CompUnit::Repository::Perl5<52007744>

  in any statement_control at /home/sena/.rakudobrew/moar-nom/install/share/nqp/lib/Perl6/Grammar.moarvm line 1

> 
```

**Comment by jonathanstowe** [comment]
Hi,
That's odd as the latest version of JSON::Marshal (v0.0.13) from the weekend has that fixed.  Can you try grabbing the most recent version and trying again?

**Comment by Altai-man** [comment]
My `.zef` was preserving the old version for some reason. Sorry for the false issue, closing.

**Comment by jonathanstowe** [comment]
No worries :)  I did check that I pushed the change as I've done that before.  Made the fix, tagged the release and then not pushed it to github.
