### ISSUE TITLE
Custom type objects aren't marshalled consistently with builtin type objects.

### ISSUE THREAD

**Issue by lefth** [jonathanstowe/JSON-Marshal#8]
Builtin (undefined) types are serialized as null. This works well, and allows round-trip conversion with JSON::Class:

```
> marshal(Int);
null
> marshal(Str);
null
```

Custom classes should be serialized the same way. Instead, they're serialized the same way as a defined class, and this either causes round-trip conversion failure, or an exception, depending on whether the class has members:

```
> class C { }
> marshal(C);
{
}
> class D { has $.i; }
> marshal(D)
Cannot look up attributes in a D type object
  in block  at D:\rakudo-2017.12\share\perl6\site\sources\0D5D5ABC9DC9B8DB1F75571789AD2F8F5FD3487A (JSON::Marshal) line 143
  in sub _marshal at D:\rakudo-2017.12\share\perl6\site\sources\0D5D5ABC9DC9B8DB1F75571789AD2F8F5FD3487A (JSON::Marshal) line 132
  in sub marshal at D:\rakudo-2017.12\share\perl6\site\sources\0D5D5ABC9DC9B8DB1F75571789AD2F8F5FD3487A (JSON::Marshal) line 172
  in block <unit> at <unknown file> line 1
```

**Comment by jonathanstowe** [comment]
Hi,
thanks, to be honest this was a scenario I hadn't even considered.  I'll take a look this afternoon.

**Comment by jonathanstowe** [comment]
I also noticed that it probably wants to be fixed for Associative and Positional type objects as well.  Thanks again.

**Comment by lefth** [comment]
`Array[MyClass]` is indeed what brought me here, but I figured it makes the most sense to start with the most basic bits. I wonder whether fixing this will also fix that case for free, since if I recall, `Array[Int]` works with undefined members. But I'm not sure I tested all the cases.

**Comment by jonathanstowe** [comment]
Hi,
that should fix;  however in order to for everything to properly round-trip then a small change to JSON::Unmarshal will be required to deal with the  ```unmarshal('null', Array)``` and ```unmarshal("null", Hash)``` cases correctly (it already works with the a custom class  like ```unmarshal("null", class C { })```.

**Comment by lefth** [comment]
@jonathanstowe  Thanks a lot! I'll file that bug with JSON::Unmarshal, and also that it seems not to work with untyped null members. (They're unmarshalled as `Mu` instead of `Any`.)
