### ISSUE TITLE
How about just a json-skip to skip attributes we do not want included...

### ISSUE THREAD

**Issue by dannymk** [jonathanstowe/JSON-Marshal#9]
I have been driving myself crazy trying to find a module that I can use with nested objects specifically classes.  Your module is pretty close however I do not want to set the properties to null to skip the values I do not want.  

It would be great if I could write a TO_JSON method or so to that returns a structure that will be marshaled by your module.  Or, just use "json-skip" on attributes we don't want included in the final JSON document.  

Something like:
```
class Something {
   has Str $.foo;
   has Str $.bar is json-skip;

}
```
 
or
```
class Something{ 
   has Str $.foo;
   has Str $.bar;
     
   method TO_JSON {
      return {
          foo => $.foo
      }
   }
}
```

**Comment by jonathanstowe** [comment]
To be honest I actually thought it did have a ```json-skip``` but my memory must be faulty.

Yeah that sounds eminently sensible, I'm sure it won't be too difficult.

**Comment by jonathanstowe** [comment]
Hi,
I've implemented ```json-skip```, I'll consider the merits of providing some mechanism to have an over-ride for the whole class but would rather cover all the use cases such that it wasn't actually necessary to be honest.
